name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: ${{ github.repository }}
      - name: Checkout ${{ github.repository_owner }}/wixoss-data
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/wixoss-data
          path: ${{ github.repository_owner }}/wixoss-data
      - name: Build ${{ github.repository }}
        run: |
          cd ${{ github.repository }}
          make update_assets_prod
          dotnet workload install wasm-tools
          dotnet workload restore
          # AOT is currently causing issues when opening card image view
          # https://github.com/MudBlazor/MudBlazor/issues/8493
          # dotnet publish -p:RunAOTCompilation=true
          dotnet publish
          echo "wx.prtn.io" > Pactmaker.Wasm/bin/Release/net8.0/publish/wwwroot/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.repository }}/Pactmaker.Wasm/bin/Release/net8.0/publish/wwwroot
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request' && github.event_name != 'merge_group'
    environment:
      name: github-pages
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v5
        continue-on-error: true
      - name: Deploy to GitHub Pages
        if: steps.setup-pages.outcome == 'success'
        uses: actions/deploy-pages@v4
